### ISSUE TITLE
Health Check for docker-compose best practice?

### ISSUE THREAD

**Issue by JAForbes** [1Password/connect#63]
Hi, I wanted to add a health check for connect-api but there's no `sh` or `bash` on the image:

> OCI runtime exec failed: exec failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown

And docker health checks largely rely on running a command, primarily curl.

I was just going to extend the base image to have net-tools but wanted to check if I was missing something obvious first.

I realise this is a docs repo, but didn't know where else to ask.  Either way it would be good to document how to have a good local development workflow with 1password connect.  I strung something workable together but little things like this make me wonder if work has already been done that I'm not aware of.

**Comment by jillianwilson** [comment]
We do have a health check endpoint that you can reach at `/health` https://developer.1password.com/docs/connect/connect-api-reference/#server-health . Does this suit your use case or do specifically want a docker health check?

**Comment by JAForbes** [comment]
The issue I'm hitting is that you need curl, or some other command line tool to hit that health endpoint via docker-composes provided health check API.  And the 1password connect containers are so heavily optimized that they do not have curl, or even a shell available to execute the health check.  Therefore I can't curl `/health` because when I attempt to, I hit this error:

> OCI runtime exec failed: exec failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown

If there was a simple example of running the health check against 1password connect within docker-compose that would be super helpful!

**Comment by mjpieters** [comment]
Docker (compose) healthchecks can only be constructed using a binary that is part of the container, e.g. curl or some other executable, with or without a parent shell, see the [docker compose `service: healthcheck: {}` documentation](https://docs.docker.com/compose/compose-file/05-services/#healthcheck) and the [docker `HEALTHCHECK` instruction](https://docs.docker.com/reference/dockerfile/#healthcheck).

The connect-api container lacks a binary that can be used for this; these are the only binaries in the image:

```
-rwxr-xr-x 0/0        27869248 2023-06-28 13:11 bin/connect-api
-rwxr-xr-x 0/0            6277 2023-02-05 21:23 usr/bin/c_rehash
-rwxr-xr-x 0/0          736792 2023-02-05 21:23 usr/bin/openssl
-rwxr-xr-x 0/0             106 2023-03-24 22:24 usr/sbin/tzconfig
```

The `openssl` binary can create network connections via `s_client -connect` but you need a shell to be able to turn that into a HTTP client capable of accessing the `/health` endpoint.

I understand and really appreciate the security consious nature of the sparse docker container, but can 1Password please include a binary that makes health checks possible? It could even be a dedicated stripped-down executable that can _only_ access the healthpoint on `localhost:${OP_HTTP_PORT:-8080}` and reports the status through an exit code.

**Comment by Jackman3005** [comment]
@mjpieters Excellent suggestion! I ran into this just today when setting it up on Coolify. It's a shame I always have to look at the status as "running (unhealthy)".

Since there are two containers, it's worth noting that both should have health checks.

**Comment by volodymyrZotov** [comment]
We might want to add this as documentation in this repo.

**Comment by oix7** [comment]
> Does this suit your use case or do specifically want a docker health check?

A docker friendly health check feature would be very appreciated.

**Comment by kimdre** [comment]
I was also  looking for this.

Here my workaround until this is resolved:
Obviously you can build your own image using the op images as the base but I was a little too lazy for that so instead I just add the necesarry binary from `busybox` with an init container during compose startup.

> [!TIP]
> If you want to simulate a kubernetes init/health probe or really dont want any additional binaries in the op image, you can also just use a sidecar container that does the healthcheck with a curl in an infinite `for` loop against both op `/health` endpoints and you just wait for the sidecar to become healthy.

```yaml
services:
  init-tools:
    image: busybox:latest
    entrypoint: "sh -xec"
    command:
      - cp /bin/busybox /tools/wget
    volumes:
      - op_tools:/tools

  op-connect-api:
    image: 1password/connect-api:latest
    ports:
      - "8080:8080"
    volumes:
      - ./1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - op_data:/home/opuser/.op/data
      - op_tools:/opt/tools:ro
    depends_on:
      init-tools:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/opt/tools/wget", "--spider", "-q", "http://127.0.0.1:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  op-connect-sync:
    image: 1password/connect-sync:latest
    ports:
      - "8081:8080"
    volumes:
      - ./1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - op_data:/home/opuser/.op/data
      - op_tools:/opt/tools:ro
    depends_on:
      init-tools:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/opt/tools/wget", "--spider", "-q", "http://127.0.0.1:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  app: # your app container
    depends_on:
      op-connect-api:
        condition: service_healthy

volumes:
  op_data:
  op_tools:
```
