### ISSUE TITLE
Problem in kubernetes `op-connect-deployment.yaml` example

### ISSUE THREAD

**Issue by renepupil** [1Password/connect#84]
The k8 deployment example at path `examples/kubernetes/op-connect-deployment.yaml`, has `chmod -f -R 600 /home/opuser/.op/config` as part of the command in the initContainer, but this path is not mounted, hence it does not have any effect on subsequent containers:

```yaml
initContainers:
  - name: sqlite-permissions
    image: alpine:3.12
    command:
      - "/bin/sh"
      - "-c"
    args:
      - "mkdir -p /home/opuser/.op/data && chown -R 999 /home/opuser && chmod -R 700 /home/opuser && chmod -f -R 600 /home/opuser/.op/config || :"
    volumeMounts:
      - mountPath: /home/opuser/.op/data
        name: shared-data
```

Only `/home/opuser/.op/data` is mounted, `chmod -f -R 600 /home/opuser/.op/config` will ONLY affect the init container.

**Did you mean `chmod -f -R 600 /home/opuser/.config` ?**

But then you had to mount the `credentials` volume as well at path `/home/opuser/.config`...

**If not, can you clarify what the intention was behind `chmod -f -R 600 /home/opuser/.op/config` ?**
