### ISSUE TITLE
sqlite database growing large

### ISSUE THREAD

**Issue by justafish** [1Password/connect#90]
The `onepassword_connect_data` docker volume has an `ACTIVITY_EVENTS` table in the sqlite database that never gets pruned - in our case it has grown to 14GB in the space of 3 weeks (and has previously filled up a disk where the volume had to be destroyed and re-made).

How should this be handled? I see there's a `OP_LOG_LEVEL` environment variable but it's not really documented what this does and what values it can be set to

**Comment by Marton6** [comment]
Thank you for reporting this issue. We will look into reproducing and fixing it.

`OP_LOG_LEVEL` only configures the amount of messages that get logged to stdout, so changing that would not have any impact on the number of activity events logged by Connect.

**Comment by justafish** [comment]
@Marton6 if at all helpful here is our docker compose file:

```
version: "3.4"

services:
  op-connect-api:
    image: 1password/connect-api:1.7.3
    ports:
      - "8080:8080"
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
    environment:
      - OP_LOG_LEVEL=error
    restart: unless-stopped
  op-connect-sync:
    image: 1password/connect-sync:1.7.3
    restart: unless-stopped
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"

volumes:
  data:
```

and we're also using this puppet module https://forge.puppet.com/modules/bryxxit/onepassword_lookup
